data: 
  input_path: 'data/vehicles_us.csv' #Just accept csv files
  sample: 0.1
  encoding: 'utf-8' 

eda: 
  representative_columns: ['model', 'price']
  plots: 
    histogram_bins: 30 #10-30
    color_palette: 'Viridis'
    plotly_template: 'plotly_white'
  thresholds: 
    null_threshold: 0.6
  output: 
    report_name: 'analysis_report.txt'
    save_plots: True
